### PR TITLE
Reduce dependencies code from lodash

### PR DESCRIPTION
**Pull request by segayuu**

### CODE REVIEW

**Comment by tcrowe** [comment]
It's kind of a pain in the butt to install each function separately. Was there something about `lodash/cloneDeep` that was problematic?

**Comment by segayuu** [comment]
thank @tcrowe!
There is a vulnerability in lodash@>=4.16.
Since warehouse does not use `defaultDeep` and `merge`, it is not a problem directly, but upgrading is necessary.
However, since I did not want to be swayed by a code that does not have such a relationship personally, I used per method packages.

**Comment by segayuu** [comment]
@tcrowe 
I agree with your opinion.
I changed to upgrade lodash itself.

**Comment by tcrowe** [comment]
Thank you @segayuu. I was going to check `lodash@4.17.10` for vulnerabilities. Did you see vulnerabilities with `npm audit`? Sometimes it's only a vulnerability if the code is running as a public server.

Also did you ever try `npm-check-updates` package? It's helpful. `ncu -an` upgrades all module versions.

**Comment by segayuu** [comment]
@tcrowe
I forgot to write after confirming that npm had published the page of vulnerability.
It is written on this page.
https://www.npmjs.com/advisories/577

**Comment by segayuu** [comment]
thank @tcrowe !
Although vscode can check the latest version, it is convenient to be able to list immediately!
I will leave the results below.

Result run `ncu -an` (this Branch)
```
 cuid               ~1.3.8  →  ~2.1.4
 chai               ^3.5.0  →  ^4.1.2
 chai-as-promised   ^5.2.0  →  ^7.1.1
 mocha              ^2.4.5  →  ^5.2.0
 sinon             ^1.17.3  →  ^6.2.0
```

**Comment by segayuu** [comment]
Personally I'd like to update all packages with this PR, but version change to PR is too big.

Even with devDependencies alone, sinon and mocha versions are pretty old, even if you update one by one, it will be a big PR with version disparity.

**Comment by tcrowe** [comment]
Oh I see. Yes the versions are very old!

**Comment by tcrowe** [comment]
https://media.giphy.com/media/wKHRk5ZUup4xq/giphy.gif

**Comment by segayuu** [comment]
@tcrowe 
Since the version difference was too large, we created two(#25, #26) PRs with only one line of difference in the package. lol

**Comment by segayuu** [comment]
@tcrowe Since there were many PRs, conflicts were expected to occur, we prioritized and merged PRs with a small number of commits.
Just like I thought, this PR conflicted.
There are other codes that I want to commit, but because of a different modification from the purpose of this PR, commit with this PR is now complete.

**Pull request merged**
