### PR TITLE
[BREAKING CHANGE] Replace constructor function to class declaration

### PR DESCRIPTION
**Pull request by segayuu**

### CODE REVIEW

**Comment by tcrowe** [comment]
I found a problem integrating it with https://github.com/hexojs/hexo.

```sh
git clone -b replace-class https://github.com/segayuu/warehouse.git
cd warehouse
npm install
cd ..
git clone https://github.com/hexojs/hexo.git
cd hexo
npm install
npm rm warehouse
npm install ../warehouse
npm test
```

The result is this error:

```
TypeError: Class constructor SchemaType cannot be invoked without 'new'
    at new SchemaTypeMoment (hexo/lib/models/types/moment.js:8:14)
    at getSchemaType (warehouse/lib/schema.js:90:10)
    at Schema.path (warehouse/lib/schema.js:118:18)
    at Schema.add (warehouse/lib/schema.js:78:10)
    at new Schema (warehouse/lib/schema.js:56:12)
    at Object.module.exports.ctx [as Page] (hexo/lib/models/page.js:9:16)
```

@segayuu Maybe you can advise me here. Unless I did something wrong we may need to adjust other modules for compatibility.

**Comment by segayuu** [comment]
I appreciate @tcrowe 's review!

This error message is not a bug.
The constructor generated by class declaration or class expression can not use `SuperClass.call()` equivalent to `super()`.
For this reason, **if the base class is defined with a class declaration or the like, derived classes will not be able to inherit classes in ES5 style.**
Due to that influence, the number of change files of this PR has become very large.

Either way, the SchemaType class and its derived classes are assumed to inherit from the outside.
If emphasis is placed on compatibility, that class group will not be able to switch to the class declaration.

**Comment by YoshinoriN** [comment]
@tcrowe @segayuu 

I think, following procedure is better way for migrate warehouse repository to class declaration.

* Migrate this ripository sorce code to class declaration (this PR)
* Warehouse package's versionup (major verup) and publish to npm
    * Also announce or write readme about breaking change.
* Update hexo main repo's warehouse package version and fix related code.

I think hexo's core repositories should to be migrate ES6 step by step.

**Comment by segayuu** [comment]
Ten days have passed since the last comment, and there are reactions with pictograms, so I will change the README.md and request a review again.

**Pull request merged**
