### PR TITLE
add misssing node 10 to ci

### PR DESCRIPTION
**Pull request by tomap**
+ fix coveralls badge

### CODE REVIEW

**Comment by tomap** [comment]
Also, can we publish a new version once this is merged?
There is a loadash vulnerability fixed by a previous PR, but never published

**Comment by segayuu** [comment]
I agree with the purpose of this PR.
However, I can not agree to do "this" PR for updating each package.

**Comment by tomap** [comment]
@segayuu : Done :)

**Comment by segayuu** [comment]
Thanks @tomap !
LGTM😄

**Pull request merged**
